### ISSUE TITLE
Internal server error on AcoustId submission

### ISSUE THREAD

**Issue by phw** [acoustid/acoustid-server#48]
The following request gives a 500 error (client credentials removed):

https://api.acoustid.org/v2/submit?user=***&fingerprint.0=AQAAjEkySemSJOiFy_BxHMRB4TgOHwcBGzwO-Dh4gIdxHD6OA7BxHPBxAziMH_BxHDiMA_BxADbwAz6OA4dxHD6OA4dxHIePA7BxAMbBAweF4_Bx8MBB4Tjg4wZwGD_g4zhwGD8A_zgAe-DB8YcO__ihI89xUDh3FFcmIfku5AAjtVXKmrOUM9sKYc22ypqtlBXaKmWVskJbpazZVilrzlLWCmXNtkJZs5WyQlulrFBCeYBAMxYRg6xhzAgM&duration.0=20&mbid.0=150ced6c-1632-4a04-a184-e4c3839b48d4&client=***&clientversion=2.2.3.final0&format=json

This was reported by a Picard users, the submission looks fine to me, but I can reproduce the internal server error.

**Comment by lalinsky** [comment]
Thanks for the report. It was a database issue and it is fixed now.

**Comment by phw** [comment]
Thanks a lot for looking into this. Unfortunately I still get the 500 error, is this expected?

**Comment by araigumaG** [comment]
I get the 500 too. I show Picard log below: 
~~~
E: 19:54:48,244 webservice._handle_reply:387: Network request error for http://api.acoustid.org:80/v2/submit: Error transferring http://api.acoustid.org:80/v2/submit - server replied: INTERNAL SERVER ERROR (QT code 401, HTTP code 500)
E: 19:54:48,245 acoustid.manager.__fingerprint_submission_finished:100: AcoustID: submission failed with error 'Error transferring http://api.acoustid.org:80/v2/submit - server replied: INTERNAL SERVER ERROR': internal error
~~~
Is it means simply 500="something happening on the server side"?

**Comment by gaston-senac** [comment]
I keep getting this error. I'm using a Mac with Picard (all software updated to latest version)

E: 19:37:29,424 webservice/__init__._handle_reply:445: Network request error for http://api.acoustid.org:80/v2/submit: Error transferring http://api.acoustid.org:80/v2/submit - server replied: INTERNAL SERVER ERROR (QT code 401, HTTP code 500)
E: 19:37:29,426 acoustid/manager._batch_submit_finished:137: AcoustID submission failed with error 'Error transferring http://api.acoustid.org:80/v2/submit - server replied: INTERNAL SERVER ERROR': internal error
